using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
	#region Tables Struct
	public partial struct Tables
	{
		
		public static readonly string TBasesNotice = @"T_Bases_Notice";
        
		public static readonly string TBasisForumList = @"T_Basis_ForumList";
        
		public static readonly string TBasisNeedPermission = @"T_Basis_NeedPermissions";
        
		public static readonly string TBasisSystemManageBox = @"T_Basis_SystemManageBox";
        
		public static readonly string TBasisTaskList = @"T_Basis_TaskList";
        
		public static readonly string TBasisUser = @"T_Basis_Users";
        
		public static readonly string TBasisUsersGroup = @"T_Basis_UsersGroup";
        
		public static readonly string TBasisWebGroup = @"T_Basis_WebGroup";
        
		public static readonly string TBasisWebPage = @"T_Basis_WebPage";
        
	}
	#endregion
    #region Schemas
    public partial class Schemas {
		
		public static TableSchema.Table TBasesNotice
		{
            get { return DataService.GetSchema("T_Bases_Notice", "Nowthwin"); }
		}
        
		public static TableSchema.Table TBasisForumList
		{
            get { return DataService.GetSchema("T_Basis_ForumList", "Nowthwin"); }
		}
        
		public static TableSchema.Table TBasisNeedPermission
		{
            get { return DataService.GetSchema("T_Basis_NeedPermissions", "Nowthwin"); }
		}
        
		public static TableSchema.Table TBasisSystemManageBox
		{
            get { return DataService.GetSchema("T_Basis_SystemManageBox", "Nowthwin"); }
		}
        
		public static TableSchema.Table TBasisTaskList
		{
            get { return DataService.GetSchema("T_Basis_TaskList", "Nowthwin"); }
		}
        
		public static TableSchema.Table TBasisUser
		{
            get { return DataService.GetSchema("T_Basis_Users", "Nowthwin"); }
		}
        
		public static TableSchema.Table TBasisUsersGroup
		{
            get { return DataService.GetSchema("T_Basis_UsersGroup", "Nowthwin"); }
		}
        
		public static TableSchema.Table TBasisWebGroup
		{
            get { return DataService.GetSchema("T_Basis_WebGroup", "Nowthwin"); }
		}
        
		public static TableSchema.Table TBasisWebPage
		{
            get { return DataService.GetSchema("T_Basis_WebPage", "Nowthwin"); }
		}
        
	
    }
    #endregion
    #region View Struct
    public partial struct Views 
    {
		
		public static readonly string VGroupWeb = @"V_GroupWebs";
        
		public static readonly string VManageListRead = @"V_ManageList_Read";
        
		public static readonly string VManageListNoRead = @"V_ManageListNoRead";
        
		public static readonly string VUser = @"V_Users";
        
		public static readonly string VUsersNeedPermission = @"V_UsersNeedPermissions";
        
    }
    #endregion
    
    #region Query Factories
	public static partial class DB
	{
        public static DataProvider _provider = DataService.Providers["Nowthwin"];
        static ISubSonicRepository _repository;
        public static ISubSonicRepository Repository 
        {
            get 
            {
                if (_repository == null)
                    return new SubSonicRepository(_provider);
                return _repository; 
            }
            set { _repository = value; }
        }
        public static Select SelectAllColumnsFrom<T>() where T : RecordBase<T>, new()
	    {
            return Repository.SelectAllColumnsFrom<T>();
	    }
	    public static Select Select()
	    {
            return Repository.Select();
	    }
	    
		public static Select Select(params string[] columns)
		{
            return Repository.Select(columns);
        }
	    
		public static Select Select(params Aggregate[] aggregates)
		{
            return Repository.Select(aggregates);
        }
   
	    public static Update Update<T>() where T : RecordBase<T>, new()
	    {
            return Repository.Update<T>();
	    }
	    
	    public static Insert Insert()
	    {
            return Repository.Insert();
	    }
	    
	    public static Delete Delete()
	    {
            return Repository.Delete();
	    }
	    
	    public static InlineQuery Query()
	    {
            return Repository.Query();
	    }
	    	    
	    
	}
    #endregion
    
}
#region Databases
public partial struct Databases 
{
	
	public static readonly string Nowthwin = @"Nowthwin";
    
}
#endregion