using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models{
    /// <summary>
    /// Strongly-typed collection for the NoGroupLine class.
    /// </summary>
    [Serializable]
    public partial class NoGroupLineCollection : ReadOnlyList<NoGroupLine, NoGroupLineCollection>
    {        
        public NoGroupLineCollection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the NoGroupLine view.
    /// </summary>
    [Serializable]
    public partial class NoGroupLine : ReadOnlyRecord<NoGroupLine>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    protected static void SetSQLProps() 
	    {
		    GetTableSchema();
	    }
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    SetSQLProps();
                }
                return BaseSchema;
            }
        }
    	
        private static void GetTableSchema() 
        {
            if(!IsSchemaInitialized)
            {
                //Schema declaration
                TableSchema.Table schema = new TableSchema.Table("NoGroupLine", TableType.View, DataService.GetInstance("Nowthwin"));
                schema.Columns = new TableSchema.TableColumnCollection();
                schema.SchemaName = @"dbo";
                //columns
                
                TableSchema.TableColumn colvarLineName = new TableSchema.TableColumn(schema);
                colvarLineName.ColumnName = "LineName";
                colvarLineName.DataType = DbType.String;
                colvarLineName.MaxLength = 255;
                colvarLineName.AutoIncrement = false;
                colvarLineName.IsNullable = true;
                colvarLineName.IsPrimaryKey = false;
                colvarLineName.IsForeignKey = false;
                colvarLineName.IsReadOnly = false;
                
                schema.Columns.Add(colvarLineName);
                
                
                BaseSchema = schema;
                //add this schema to the provider
                //so we can query it later
                DataService.Providers["Nowthwin"].AddSchema("NoGroupLine",schema);
            }
        }
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public NoGroupLine()
	    {
            SetSQLProps();
            SetDefaults();
            MarkNew();
        }
        public NoGroupLine(bool useDatabaseDefaults)
	    {
		    SetSQLProps();
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			MarkNew();
	    }
	    
	    public NoGroupLine(object keyID)
	    {
		    SetSQLProps();
		    LoadByKey(keyID);
	    }
    	 
	    public NoGroupLine(string columnName, object columnValue)
        {
            SetSQLProps();
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("LineName")]
        [Bindable(true)]
        public string LineName 
	    {
		    get
		    {
			    return GetColumnValue<string>("LineName");
		    }
            set 
		    {
			    SetColumnValue("LineName", value);
            }
        }
	    
	    #endregion
    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string LineName = @"LineName";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
