using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
    /// <summary>
    /// Controller class for quhao
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class QuhaoController
    {
        // Preload our schema..
        Quhao thisSchemaLoad = new Quhao();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public QuhaoCollection FetchAll()
        {
            QuhaoCollection coll = new QuhaoCollection();
            Query qry = new Query(Quhao.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public QuhaoCollection FetchByID(object Id)
        {
            QuhaoCollection coll = new QuhaoCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public QuhaoCollection FetchByQuery(Query qry)
        {
            QuhaoCollection coll = new QuhaoCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (Quhao.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (Quhao.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string QuhaoX,string Gjfl)
	    {
		    Quhao item = new Quhao();
		    
            item.QuhaoX = QuhaoX;
            
            item.Gjfl = Gjfl;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string QuhaoX,int Id,string Gjfl)
	    {
		    Quhao item = new Quhao();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.QuhaoX = QuhaoX;
				
			item.Id = Id;
				
			item.Gjfl = Gjfl;
				
	        item.Save(UserName);
	    }
    }
}
