using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
	/// <summary>
	/// Strongly-typed collection for the Quhao class.
	/// </summary>
    [Serializable]
	public partial class QuhaoCollection : ActiveList<Quhao, QuhaoCollection>
	{	   
		public QuhaoCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>QuhaoCollection</returns>
		public QuhaoCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                Quhao o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the quhao table.
	/// </summary>
	[Serializable]
	public partial class Quhao : ActiveRecord<Quhao>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public Quhao()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public Quhao(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public Quhao(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public Quhao(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("quhao", TableType.Table, DataService.GetInstance("Nowthwin"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarQuhaoX = new TableSchema.TableColumn(schema);
				colvarQuhaoX.ColumnName = "quhao";
				colvarQuhaoX.DataType = DbType.String;
				colvarQuhaoX.MaxLength = -1;
				colvarQuhaoX.AutoIncrement = false;
				colvarQuhaoX.IsNullable = true;
				colvarQuhaoX.IsPrimaryKey = false;
				colvarQuhaoX.IsForeignKey = false;
				colvarQuhaoX.IsReadOnly = false;
				colvarQuhaoX.DefaultSetting = @"";
				colvarQuhaoX.ForeignKeyTableName = "";
				schema.Columns.Add(colvarQuhaoX);
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarGjfl = new TableSchema.TableColumn(schema);
				colvarGjfl.ColumnName = "gjfl";
				colvarGjfl.DataType = DbType.String;
				colvarGjfl.MaxLength = 255;
				colvarGjfl.AutoIncrement = false;
				colvarGjfl.IsNullable = true;
				colvarGjfl.IsPrimaryKey = false;
				colvarGjfl.IsForeignKey = false;
				colvarGjfl.IsReadOnly = false;
				colvarGjfl.DefaultSetting = @"";
				colvarGjfl.ForeignKeyTableName = "";
				schema.Columns.Add(colvarGjfl);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Nowthwin"].AddSchema("quhao",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("QuhaoX")]
		[Bindable(true)]
		public string QuhaoX 
		{
			get { return GetColumnValue<string>(Columns.QuhaoX); }
			set { SetColumnValue(Columns.QuhaoX, value); }
		}
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("Gjfl")]
		[Bindable(true)]
		public string Gjfl 
		{
			get { return GetColumnValue<string>(Columns.Gjfl); }
			set { SetColumnValue(Columns.Gjfl, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varQuhaoX,string varGjfl)
		{
			Quhao item = new Quhao();
			
			item.QuhaoX = varQuhaoX;
			
			item.Gjfl = varGjfl;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(string varQuhaoX,int varId,string varGjfl)
		{
			Quhao item = new Quhao();
			
				item.QuhaoX = varQuhaoX;
			
				item.Id = varId;
			
				item.Gjfl = varGjfl;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn QuhaoXColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn GjflColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string QuhaoX = @"quhao";
			 public static string Id = @"id";
			 public static string Gjfl = @"gjfl";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
