using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
    /// <summary>
    /// Controller class for T_ApsClientClickCount
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TApsClientClickCountController
    {
        // Preload our schema..
        TApsClientClickCount thisSchemaLoad = new TApsClientClickCount();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TApsClientClickCountCollection FetchAll()
        {
            TApsClientClickCountCollection coll = new TApsClientClickCountCollection();
            Query qry = new Query(TApsClientClickCount.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TApsClientClickCountCollection FetchByID(object Id)
        {
            TApsClientClickCountCollection coll = new TApsClientClickCountCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TApsClientClickCountCollection FetchByQuery(Query qry)
        {
            TApsClientClickCountCollection coll = new TApsClientClickCountCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TApsClientClickCount.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TApsClientClickCount.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string CreateDate,int? ClickCount,int? NowClickCount)
	    {
		    TApsClientClickCount item = new TApsClientClickCount();
		    
            item.CreateDate = CreateDate;
            
            item.ClickCount = ClickCount;
            
            item.NowClickCount = NowClickCount;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string CreateDate,int? ClickCount,int? NowClickCount)
	    {
		    TApsClientClickCount item = new TApsClientClickCount();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.CreateDate = CreateDate;
				
			item.ClickCount = ClickCount;
				
			item.NowClickCount = NowClickCount;
				
	        item.Save(UserName);
	    }
    }
}
