using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
	/// <summary>
	/// Strongly-typed collection for the TBasisForumList class.
	/// </summary>
    [Serializable]
	public partial class TBasisForumListCollection : ActiveList<TBasisForumList, TBasisForumListCollection>
	{	   
		public TBasisForumListCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TBasisForumListCollection</returns>
		public TBasisForumListCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TBasisForumList o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the T_Basis_ForumList table.
	/// </summary>
	[Serializable]
	public partial class TBasisForumList : ActiveRecord<TBasisForumList>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TBasisForumList()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TBasisForumList(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TBasisForumList(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TBasisForumList(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("T_Basis_ForumList", TableType.Table, DataService.GetInstance("Nowthwin"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarForumName = new TableSchema.TableColumn(schema);
				colvarForumName.ColumnName = "ForumName";
				colvarForumName.DataType = DbType.String;
				colvarForumName.MaxLength = 100;
				colvarForumName.AutoIncrement = false;
				colvarForumName.IsNullable = true;
				colvarForumName.IsPrimaryKey = false;
				colvarForumName.IsForeignKey = false;
				colvarForumName.IsReadOnly = false;
				colvarForumName.DefaultSetting = @"";
				colvarForumName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarForumName);
				
				TableSchema.TableColumn colvarForumDescription = new TableSchema.TableColumn(schema);
				colvarForumDescription.ColumnName = "ForumDescription";
				colvarForumDescription.DataType = DbType.String;
				colvarForumDescription.MaxLength = 255;
				colvarForumDescription.AutoIncrement = false;
				colvarForumDescription.IsNullable = true;
				colvarForumDescription.IsPrimaryKey = false;
				colvarForumDescription.IsForeignKey = false;
				colvarForumDescription.IsReadOnly = false;
				colvarForumDescription.DefaultSetting = @"";
				colvarForumDescription.ForeignKeyTableName = "";
				schema.Columns.Add(colvarForumDescription);
				
				TableSchema.TableColumn colvarForumIcon = new TableSchema.TableColumn(schema);
				colvarForumIcon.ColumnName = "ForumIcon";
				colvarForumIcon.DataType = DbType.String;
				colvarForumIcon.MaxLength = 100;
				colvarForumIcon.AutoIncrement = false;
				colvarForumIcon.IsNullable = true;
				colvarForumIcon.IsPrimaryKey = false;
				colvarForumIcon.IsForeignKey = false;
				colvarForumIcon.IsReadOnly = false;
				colvarForumIcon.DefaultSetting = @"";
				colvarForumIcon.ForeignKeyTableName = "";
				schema.Columns.Add(colvarForumIcon);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Nowthwin"].AddSchema("T_Basis_ForumList",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("ForumName")]
		[Bindable(true)]
		public string ForumName 
		{
			get { return GetColumnValue<string>(Columns.ForumName); }
			set { SetColumnValue(Columns.ForumName, value); }
		}
		  
		[XmlAttribute("ForumDescription")]
		[Bindable(true)]
		public string ForumDescription 
		{
			get { return GetColumnValue<string>(Columns.ForumDescription); }
			set { SetColumnValue(Columns.ForumDescription, value); }
		}
		  
		[XmlAttribute("ForumIcon")]
		[Bindable(true)]
		public string ForumIcon 
		{
			get { return GetColumnValue<string>(Columns.ForumIcon); }
			set { SetColumnValue(Columns.ForumIcon, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varForumName,string varForumDescription,string varForumIcon)
		{
			TBasisForumList item = new TBasisForumList();
			
			item.ForumName = varForumName;
			
			item.ForumDescription = varForumDescription;
			
			item.ForumIcon = varForumIcon;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varForumName,string varForumDescription,string varForumIcon)
		{
			TBasisForumList item = new TBasisForumList();
			
				item.Id = varId;
			
				item.ForumName = varForumName;
			
				item.ForumDescription = varForumDescription;
			
				item.ForumIcon = varForumIcon;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn ForumNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn ForumDescriptionColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn ForumIconColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string ForumName = @"ForumName";
			 public static string ForumDescription = @"ForumDescription";
			 public static string ForumIcon = @"ForumIcon";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
