using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
    /// <summary>
    /// Controller class for T_Bases_Notice
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TBasesNoticeController
    {
        // Preload our schema..
        TBasesNotice thisSchemaLoad = new TBasesNotice();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TBasesNoticeCollection FetchAll()
        {
            TBasesNoticeCollection coll = new TBasesNoticeCollection();
            Query qry = new Query(TBasesNotice.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TBasesNoticeCollection FetchByID(object Id)
        {
            TBasesNoticeCollection coll = new TBasesNoticeCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TBasesNoticeCollection FetchByQuery(Query qry)
        {
            TBasesNoticeCollection coll = new TBasesNoticeCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TBasesNotice.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TBasesNotice.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Title,string Url,DateTime? CreateTime,int? Uid)
	    {
		    TBasesNotice item = new TBasesNotice();
		    
            item.Title = Title;
            
            item.Url = Url;
            
            item.CreateTime = CreateTime;
            
            item.Uid = Uid;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Title,string Url,DateTime? CreateTime,int? Uid)
	    {
		    TBasesNotice item = new TBasesNotice();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Title = Title;
				
			item.Url = Url;
				
			item.CreateTime = CreateTime;
				
			item.Uid = Uid;
				
	        item.Save(UserName);
	    }
    }
}
