using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
    /// <summary>
    /// Controller class for T_Basis_Users
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TBasisUserController
    {
        // Preload our schema..
        TBasisUser thisSchemaLoad = new TBasisUser();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TBasisUserCollection FetchAll()
        {
            TBasisUserCollection coll = new TBasisUserCollection();
            Query qry = new Query(TBasisUser.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TBasisUserCollection FetchByID(object Account)
        {
            TBasisUserCollection coll = new TBasisUserCollection().Where("Account", Account).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TBasisUserCollection FetchByQuery(Query qry)
        {
            TBasisUserCollection coll = new TBasisUserCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Account)
        {
            return (TBasisUser.Delete(Account) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Account)
        {
            return (TBasisUser.Destroy(Account) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string UserName,string UserPwd,string Email,string Telphone,string Account,int SecurityLock,string HavingPage,int UsersGroup)
	    {
		    TBasisUser item = new TBasisUser();
		    
            item.UserName = UserName;
            
            item.UserPwd = UserPwd;
            
            item.Email = Email;
            
            item.Telphone = Telphone;
            
            item.Account = Account;
            
            item.SecurityLock = SecurityLock;
            
            item.HavingPage = HavingPage;
            
            item.UsersGroup = UsersGroup;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string UserName,string UserPwd,string Email,string Telphone,string Account,int SecurityLock,string HavingPage,int UsersGroup)
	    {
		    TBasisUser item = new TBasisUser();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.UserName = UserName;
				
			item.UserPwd = UserPwd;
				
			item.Email = Email;
				
			item.Telphone = Telphone;
				
			item.Account = Account;
				
			item.SecurityLock = SecurityLock;
				
			item.HavingPage = HavingPage;
				
			item.UsersGroup = UsersGroup;
				
	        item.Save(UserName);
	    }
    }
}
