using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
    /// <summary>
    /// Controller class for T_Basis_WebPage
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TBasisWebPageController
    {
        // Preload our schema..
        TBasisWebPage thisSchemaLoad = new TBasisWebPage();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TBasisWebPageCollection FetchAll()
        {
            TBasisWebPageCollection coll = new TBasisWebPageCollection();
            Query qry = new Query(TBasisWebPage.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TBasisWebPageCollection FetchByID(object Id)
        {
            TBasisWebPageCollection coll = new TBasisWebPageCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TBasisWebPageCollection FetchByQuery(Query qry)
        {
            TBasisWebPageCollection coll = new TBasisWebPageCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TBasisWebPage.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TBasisWebPage.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int Id,string PageName,string PageUrl,int Locked,int? Jurisdiction,int? GroupId,int? ShowMenu)
	    {
		    TBasisWebPage item = new TBasisWebPage();
		    
            item.Id = Id;
            
            item.PageName = PageName;
            
            item.PageUrl = PageUrl;
            
            item.Locked = Locked;
            
            item.Jurisdiction = Jurisdiction;
            
            item.GroupId = GroupId;
            
            item.ShowMenu = ShowMenu;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string PageName,string PageUrl,int Locked,int? Jurisdiction,int? GroupId,int? ShowMenu)
	    {
		    TBasisWebPage item = new TBasisWebPage();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.PageName = PageName;
				
			item.PageUrl = PageUrl;
				
			item.Locked = Locked;
				
			item.Jurisdiction = Jurisdiction;
				
			item.GroupId = GroupId;
				
			item.ShowMenu = ShowMenu;
				
	        item.Save(UserName);
	    }
    }
}
