using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
    /// <summary>
    /// Controller class for T_Basis_UsersGroup
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TBasisUsersGroupController
    {
        // Preload our schema..
        TBasisUsersGroup thisSchemaLoad = new TBasisUsersGroup();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TBasisUsersGroupCollection FetchAll()
        {
            TBasisUsersGroupCollection coll = new TBasisUsersGroupCollection();
            Query qry = new Query(TBasisUsersGroup.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TBasisUsersGroupCollection FetchByID(object Id)
        {
            TBasisUsersGroupCollection coll = new TBasisUsersGroupCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TBasisUsersGroupCollection FetchByQuery(Query qry)
        {
            TBasisUsersGroupCollection coll = new TBasisUsersGroupCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TBasisUsersGroup.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TBasisUsersGroup.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string GroupName,int? GroupLock)
	    {
		    TBasisUsersGroup item = new TBasisUsersGroup();
		    
            item.GroupName = GroupName;
            
            item.GroupLock = GroupLock;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string GroupName,int? GroupLock)
	    {
		    TBasisUsersGroup item = new TBasisUsersGroup();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.GroupName = GroupName;
				
			item.GroupLock = GroupLock;
				
	        item.Save(UserName);
	    }
    }
}
