using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
    /// <summary>
    /// Controller class for T_Basis_TaskList
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TBasisTaskListController
    {
        // Preload our schema..
        TBasisTaskList thisSchemaLoad = new TBasisTaskList();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TBasisTaskListCollection FetchAll()
        {
            TBasisTaskListCollection coll = new TBasisTaskListCollection();
            Query qry = new Query(TBasisTaskList.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TBasisTaskListCollection FetchByID(object Id)
        {
            TBasisTaskListCollection coll = new TBasisTaskListCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TBasisTaskListCollection FetchByQuery(Query qry)
        {
            TBasisTaskListCollection coll = new TBasisTaskListCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TBasisTaskList.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TBasisTaskList.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string TaskContext,string TaskType,int? CreateUser,DateTime? CreateDate,string TaskState,int? AssignUser,string UpdateDataUsers,DateTime? StartTime,DateTime? EndTime)
	    {
		    TBasisTaskList item = new TBasisTaskList();
		    
            item.TaskContext = TaskContext;
            
            item.TaskType = TaskType;
            
            item.CreateUser = CreateUser;
            
            item.CreateDate = CreateDate;
            
            item.TaskState = TaskState;
            
            item.AssignUser = AssignUser;
            
            item.UpdateDataUsers = UpdateDataUsers;
            
            item.StartTime = StartTime;
            
            item.EndTime = EndTime;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string TaskContext,string TaskType,int? CreateUser,DateTime? CreateDate,string TaskState,int? AssignUser,string UpdateDataUsers,DateTime? StartTime,DateTime? EndTime)
	    {
		    TBasisTaskList item = new TBasisTaskList();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.TaskContext = TaskContext;
				
			item.TaskType = TaskType;
				
			item.CreateUser = CreateUser;
				
			item.CreateDate = CreateDate;
				
			item.TaskState = TaskState;
				
			item.AssignUser = AssignUser;
				
			item.UpdateDataUsers = UpdateDataUsers;
				
			item.StartTime = StartTime;
				
			item.EndTime = EndTime;
				
	        item.Save(UserName);
	    }
    }
}
