using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
    /// <summary>
    /// Controller class for T_Basis_ForumList
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TBasisForumListController
    {
        // Preload our schema..
        TBasisForumList thisSchemaLoad = new TBasisForumList();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TBasisForumListCollection FetchAll()
        {
            TBasisForumListCollection coll = new TBasisForumListCollection();
            Query qry = new Query(TBasisForumList.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TBasisForumListCollection FetchByID(object Id)
        {
            TBasisForumListCollection coll = new TBasisForumListCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TBasisForumListCollection FetchByQuery(Query qry)
        {
            TBasisForumListCollection coll = new TBasisForumListCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TBasisForumList.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TBasisForumList.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string ForumName,string ForumDescription,string ForumIcon)
	    {
		    TBasisForumList item = new TBasisForumList();
		    
            item.ForumName = ForumName;
            
            item.ForumDescription = ForumDescription;
            
            item.ForumIcon = ForumIcon;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string ForumName,string ForumDescription,string ForumIcon)
	    {
		    TBasisForumList item = new TBasisForumList();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.ForumName = ForumName;
				
			item.ForumDescription = ForumDescription;
				
			item.ForumIcon = ForumIcon;
				
	        item.Save(UserName);
	    }
    }
}
