using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
    /// <summary>
    /// Controller class for T_Basis_NeedPermissions
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TBasisNeedPermissionController
    {
        // Preload our schema..
        TBasisNeedPermission thisSchemaLoad = new TBasisNeedPermission();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TBasisNeedPermissionCollection FetchAll()
        {
            TBasisNeedPermissionCollection coll = new TBasisNeedPermissionCollection();
            Query qry = new Query(TBasisNeedPermission.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TBasisNeedPermissionCollection FetchByID(object Id)
        {
            TBasisNeedPermissionCollection coll = new TBasisNeedPermissionCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TBasisNeedPermissionCollection FetchByQuery(Query qry)
        {
            TBasisNeedPermissionCollection coll = new TBasisNeedPermissionCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TBasisNeedPermission.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TBasisNeedPermission.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int UserID,int PageID,string Content,DateTime CreateTime)
	    {
		    TBasisNeedPermission item = new TBasisNeedPermission();
		    
            item.UserID = UserID;
            
            item.PageID = PageID;
            
            item.Content = Content;
            
            item.CreateTime = CreateTime;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int UserID,int PageID,string Content,DateTime CreateTime)
	    {
		    TBasisNeedPermission item = new TBasisNeedPermission();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.UserID = UserID;
				
			item.PageID = PageID;
				
			item.Content = Content;
				
			item.CreateTime = CreateTime;
				
	        item.Save(UserName);
	    }
    }
}
