using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
	/// <summary>
	/// Strongly-typed collection for the TClientLineGroup class.
	/// </summary>
    [Serializable]
	public partial class TClientLineGroupCollection : ActiveList<TClientLineGroup, TClientLineGroupCollection>
	{	   
		public TClientLineGroupCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TClientLineGroupCollection</returns>
		public TClientLineGroupCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TClientLineGroup o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the T_ClientLineGroup table.
	/// </summary>
	[Serializable]
	public partial class TClientLineGroup : ActiveRecord<TClientLineGroup>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TClientLineGroup()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TClientLineGroup(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TClientLineGroup(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TClientLineGroup(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("T_ClientLineGroup", TableType.Table, DataService.GetInstance("Nowthwin"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "ID";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarLineName = new TableSchema.TableColumn(schema);
				colvarLineName.ColumnName = "LineName";
				colvarLineName.DataType = DbType.String;
				colvarLineName.MaxLength = 255;
				colvarLineName.AutoIncrement = false;
				colvarLineName.IsNullable = false;
				colvarLineName.IsPrimaryKey = false;
				colvarLineName.IsForeignKey = false;
				colvarLineName.IsReadOnly = false;
				colvarLineName.DefaultSetting = @"";
				colvarLineName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLineName);
				
				TableSchema.TableColumn colvarGroupName = new TableSchema.TableColumn(schema);
				colvarGroupName.ColumnName = "GroupName";
				colvarGroupName.DataType = DbType.String;
				colvarGroupName.MaxLength = 255;
				colvarGroupName.AutoIncrement = false;
				colvarGroupName.IsNullable = false;
				colvarGroupName.IsPrimaryKey = false;
				colvarGroupName.IsForeignKey = false;
				colvarGroupName.IsReadOnly = false;
				colvarGroupName.DefaultSetting = @"";
				colvarGroupName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarGroupName);
				
				TableSchema.TableColumn colvarMaxCount = new TableSchema.TableColumn(schema);
				colvarMaxCount.ColumnName = "MaxCount";
				colvarMaxCount.DataType = DbType.Int64;
				colvarMaxCount.MaxLength = 0;
				colvarMaxCount.AutoIncrement = false;
				colvarMaxCount.IsNullable = true;
				colvarMaxCount.IsPrimaryKey = false;
				colvarMaxCount.IsForeignKey = false;
				colvarMaxCount.IsReadOnly = false;
				colvarMaxCount.DefaultSetting = @"";
				colvarMaxCount.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMaxCount);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Nowthwin"].AddSchema("T_ClientLineGroup",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("LineName")]
		[Bindable(true)]
		public string LineName 
		{
			get { return GetColumnValue<string>(Columns.LineName); }
			set { SetColumnValue(Columns.LineName, value); }
		}
		  
		[XmlAttribute("GroupName")]
		[Bindable(true)]
		public string GroupName 
		{
			get { return GetColumnValue<string>(Columns.GroupName); }
			set { SetColumnValue(Columns.GroupName, value); }
		}
		  
		[XmlAttribute("MaxCount")]
		[Bindable(true)]
		public long? MaxCount 
		{
			get { return GetColumnValue<long?>(Columns.MaxCount); }
			set { SetColumnValue(Columns.MaxCount, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varLineName,string varGroupName,long? varMaxCount)
		{
			TClientLineGroup item = new TClientLineGroup();
			
			item.LineName = varLineName;
			
			item.GroupName = varGroupName;
			
			item.MaxCount = varMaxCount;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varLineName,string varGroupName,long? varMaxCount)
		{
			TClientLineGroup item = new TClientLineGroup();
			
				item.Id = varId;
			
				item.LineName = varLineName;
			
				item.GroupName = varGroupName;
			
				item.MaxCount = varMaxCount;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn LineNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn GroupNameColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn MaxCountColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"ID";
			 public static string LineName = @"LineName";
			 public static string GroupName = @"GroupName";
			 public static string MaxCount = @"MaxCount";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
