using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
    /// <summary>
    /// Controller class for T_ClientLineGroup
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TClientLineGroupController
    {
        // Preload our schema..
        TClientLineGroup thisSchemaLoad = new TClientLineGroup();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TClientLineGroupCollection FetchAll()
        {
            TClientLineGroupCollection coll = new TClientLineGroupCollection();
            Query qry = new Query(TClientLineGroup.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TClientLineGroupCollection FetchByID(object Id)
        {
            TClientLineGroupCollection coll = new TClientLineGroupCollection().Where("ID", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TClientLineGroupCollection FetchByQuery(Query qry)
        {
            TClientLineGroupCollection coll = new TClientLineGroupCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TClientLineGroup.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TClientLineGroup.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string LineName,string GroupName,long? MaxCount)
	    {
		    TClientLineGroup item = new TClientLineGroup();
		    
            item.LineName = LineName;
            
            item.GroupName = GroupName;
            
            item.MaxCount = MaxCount;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string LineName,string GroupName,long? MaxCount)
	    {
		    TClientLineGroup item = new TClientLineGroup();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.LineName = LineName;
				
			item.GroupName = GroupName;
				
			item.MaxCount = MaxCount;
				
	        item.Save(UserName);
	    }
    }
}
