using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
	/// <summary>
	/// Strongly-typed collection for the TCountry class.
	/// </summary>
    [Serializable]
	public partial class TCountryCollection : ActiveList<TCountry, TCountryCollection>
	{	   
		public TCountryCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TCountryCollection</returns>
		public TCountryCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TCountry o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the T_Country table.
	/// </summary>
	[Serializable]
	public partial class TCountry : ActiveRecord<TCountry>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TCountry()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TCountry(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TCountry(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TCountry(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("T_Country", TableType.Table, DataService.GetInstance("Nowthwin"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarScyspdqz = new TableSchema.TableColumn(schema);
				colvarScyspdqz.ColumnName = "scyspdqz";
				colvarScyspdqz.DataType = DbType.String;
				colvarScyspdqz.MaxLength = 255;
				colvarScyspdqz.AutoIncrement = false;
				colvarScyspdqz.IsNullable = false;
				colvarScyspdqz.IsPrimaryKey = true;
				colvarScyspdqz.IsForeignKey = false;
				colvarScyspdqz.IsReadOnly = false;
				colvarScyspdqz.DefaultSetting = @"";
				colvarScyspdqz.ForeignKeyTableName = "";
				schema.Columns.Add(colvarScyspdqz);
				
				TableSchema.TableColumn colvarGjfl = new TableSchema.TableColumn(schema);
				colvarGjfl.ColumnName = "Gjfl";
				colvarGjfl.DataType = DbType.String;
				colvarGjfl.MaxLength = 255;
				colvarGjfl.AutoIncrement = false;
				colvarGjfl.IsNullable = true;
				colvarGjfl.IsPrimaryKey = false;
				colvarGjfl.IsForeignKey = false;
				colvarGjfl.IsReadOnly = false;
				colvarGjfl.DefaultSetting = @"";
				colvarGjfl.ForeignKeyTableName = "";
				schema.Columns.Add(colvarGjfl);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Nowthwin"].AddSchema("T_Country",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Scyspdqz")]
		[Bindable(true)]
		public string Scyspdqz 
		{
			get { return GetColumnValue<string>(Columns.Scyspdqz); }
			set { SetColumnValue(Columns.Scyspdqz, value); }
		}
		  
		[XmlAttribute("Gjfl")]
		[Bindable(true)]
		public string Gjfl 
		{
			get { return GetColumnValue<string>(Columns.Gjfl); }
			set { SetColumnValue(Columns.Gjfl, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varScyspdqz,string varGjfl)
		{
			TCountry item = new TCountry();
			
			item.Scyspdqz = varScyspdqz;
			
			item.Gjfl = varGjfl;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(string varScyspdqz,string varGjfl)
		{
			TCountry item = new TCountry();
			
				item.Scyspdqz = varScyspdqz;
			
				item.Gjfl = varGjfl;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn ScyspdqzColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn GjflColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Scyspdqz = @"scyspdqz";
			 public static string Gjfl = @"Gjfl";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
