using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models
{
    /// <summary>
    /// Controller class for T_Country
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TCountryController
    {
        // Preload our schema..
        TCountry thisSchemaLoad = new TCountry();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TCountryCollection FetchAll()
        {
            TCountryCollection coll = new TCountryCollection();
            Query qry = new Query(TCountry.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TCountryCollection FetchByID(object Scyspdqz)
        {
            TCountryCollection coll = new TCountryCollection().Where("scyspdqz", Scyspdqz).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TCountryCollection FetchByQuery(Query qry)
        {
            TCountryCollection coll = new TCountryCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Scyspdqz)
        {
            return (TCountry.Delete(Scyspdqz) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Scyspdqz)
        {
            return (TCountry.Destroy(Scyspdqz) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Scyspdqz,string Gjfl)
	    {
		    TCountry item = new TCountry();
		    
            item.Scyspdqz = Scyspdqz;
            
            item.Gjfl = Gjfl;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string Scyspdqz,string Gjfl)
	    {
		    TCountry item = new TCountry();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Scyspdqz = Scyspdqz;
				
			item.Gjfl = Gjfl;
				
	        item.Save(UserName);
	    }
    }
}
