using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Models{
    /// <summary>
    /// Strongly-typed collection for the VResourcesAll class.
    /// </summary>
    [Serializable]
    public partial class VResourcesAllCollection : ReadOnlyList<VResourcesAll, VResourcesAllCollection>
    {        
        public VResourcesAllCollection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the V_ResourcesAll view.
    /// </summary>
    [Serializable]
    public partial class VResourcesAll : ReadOnlyRecord<VResourcesAll>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    protected static void SetSQLProps() 
	    {
		    GetTableSchema();
	    }
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    SetSQLProps();
                }
                return BaseSchema;
            }
        }
    	
        private static void GetTableSchema() 
        {
            if(!IsSchemaInitialized)
            {
                //Schema declaration
                TableSchema.Table schema = new TableSchema.Table("V_ResourcesAll", TableType.View, DataService.GetInstance("Nowthwin"));
                schema.Columns = new TableSchema.TableColumnCollection();
                schema.SchemaName = @"dbo";
                //columns
                
                TableSchema.TableColumn colvarResourcesCode = new TableSchema.TableColumn(schema);
                colvarResourcesCode.ColumnName = "resourcesCode";
                colvarResourcesCode.DataType = DbType.AnsiString;
                colvarResourcesCode.MaxLength = 50;
                colvarResourcesCode.AutoIncrement = false;
                colvarResourcesCode.IsNullable = false;
                colvarResourcesCode.IsPrimaryKey = false;
                colvarResourcesCode.IsForeignKey = false;
                colvarResourcesCode.IsReadOnly = false;
                
                schema.Columns.Add(colvarResourcesCode);
                
                TableSchema.TableColumn colvarResources = new TableSchema.TableColumn(schema);
                colvarResources.ColumnName = "resources";
                colvarResources.DataType = DbType.AnsiString;
                colvarResources.MaxLength = 10;
                colvarResources.AutoIncrement = false;
                colvarResources.IsNullable = false;
                colvarResources.IsPrimaryKey = false;
                colvarResources.IsForeignKey = false;
                colvarResources.IsReadOnly = false;
                
                schema.Columns.Add(colvarResources);
                
                TableSchema.TableColumn colvarResourcesName = new TableSchema.TableColumn(schema);
                colvarResourcesName.ColumnName = "resourcesName";
                colvarResourcesName.DataType = DbType.AnsiString;
                colvarResourcesName.MaxLength = 50;
                colvarResourcesName.AutoIncrement = false;
                colvarResourcesName.IsNullable = true;
                colvarResourcesName.IsPrimaryKey = false;
                colvarResourcesName.IsForeignKey = false;
                colvarResourcesName.IsReadOnly = false;
                
                schema.Columns.Add(colvarResourcesName);
                
                TableSchema.TableColumn colvarDateType = new TableSchema.TableColumn(schema);
                colvarDateType.ColumnName = "DateType";
                colvarDateType.DataType = DbType.AnsiString;
                colvarDateType.MaxLength = 50;
                colvarDateType.AutoIncrement = false;
                colvarDateType.IsNullable = true;
                colvarDateType.IsPrimaryKey = false;
                colvarDateType.IsForeignKey = false;
                colvarDateType.IsReadOnly = false;
                
                schema.Columns.Add(colvarDateType);
                
                TableSchema.TableColumn colvarType = new TableSchema.TableColumn(schema);
                colvarType.ColumnName = "type";
                colvarType.DataType = DbType.AnsiString;
                colvarType.MaxLength = 50;
                colvarType.AutoIncrement = false;
                colvarType.IsNullable = true;
                colvarType.IsPrimaryKey = false;
                colvarType.IsForeignKey = false;
                colvarType.IsReadOnly = false;
                
                schema.Columns.Add(colvarType);
                
                
                BaseSchema = schema;
                //add this schema to the provider
                //so we can query it later
                DataService.Providers["Nowthwin"].AddSchema("V_ResourcesAll",schema);
            }
        }
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public VResourcesAll()
	    {
            SetSQLProps();
            SetDefaults();
            MarkNew();
        }
        public VResourcesAll(bool useDatabaseDefaults)
	    {
		    SetSQLProps();
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			MarkNew();
	    }
	    
	    public VResourcesAll(object keyID)
	    {
		    SetSQLProps();
		    LoadByKey(keyID);
	    }
    	 
	    public VResourcesAll(string columnName, object columnValue)
        {
            SetSQLProps();
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("ResourcesCode")]
        [Bindable(true)]
        public string ResourcesCode 
	    {
		    get
		    {
			    return GetColumnValue<string>("resourcesCode");
		    }
            set 
		    {
			    SetColumnValue("resourcesCode", value);
            }
        }
	      
        [XmlAttribute("Resources")]
        [Bindable(true)]
        public string Resources 
	    {
		    get
		    {
			    return GetColumnValue<string>("resources");
		    }
            set 
		    {
			    SetColumnValue("resources", value);
            }
        }
	      
        [XmlAttribute("ResourcesName")]
        [Bindable(true)]
        public string ResourcesName 
	    {
		    get
		    {
			    return GetColumnValue<string>("resourcesName");
		    }
            set 
		    {
			    SetColumnValue("resourcesName", value);
            }
        }
	      
        [XmlAttribute("DateType")]
        [Bindable(true)]
        public string DateType 
	    {
		    get
		    {
			    return GetColumnValue<string>("DateType");
		    }
            set 
		    {
			    SetColumnValue("DateType", value);
            }
        }
	      
        [XmlAttribute("Type")]
        [Bindable(true)]
        public string Type 
	    {
		    get
		    {
			    return GetColumnValue<string>("type");
		    }
            set 
		    {
			    SetColumnValue("type", value);
            }
        }
	    
	    #endregion
    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string ResourcesCode = @"resourcesCode";
            
            public static string Resources = @"resources";
            
            public static string ResourcesName = @"resourcesName";
            
            public static string DateType = @"DateType";
            
            public static string Type = @"type";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
